### ISSUE TITLE
Use `oif_interface_` prefix for C implementations

### ISSUE THREAD

**Issue by dmitry-kabanov** [MaRDI4NFDI/open-interfaces#731]
**Issue description**:
There is a lack of "namespacing" in C implementations right now: precisely, functions are called the same way as they called, e. g., in Python. It would be better if all functions have prefixes `oif_interface_` so that it would be clear  in the implementation, which functions implement a given interface.
 
Also, on the implementation side the interfaces have this prefix, therefore, their inclusion into implementations is useless as then C compiler does not check conformance, actually.
 
**TODOS**: 

- [ ] Modify `dispatch_c`  module so that each function invocation of a C implementation contains prefix `oif_interface_` `prepended` to the `method` name passed as an argument to `call_impl_method`
- [ ] Probably, C implementations should carry with them the information about what interface they implement: that is, interface name must be copied during implementation initialization
- [ ] Modify existing C implementations such as `c_qeq`, `c_lapack`, and `sundials_cvode` so that the function names have this prefix
